cat/main/routes.py
from flask import render_template, request, redirect, url_for, Blueprint
from flask_login import login_required
from cat.models import Result
from sqlalchemy import desc


main = Blueprint('main', __name__)

@main.route("/")
@main.route("/index")
@login_required
def index():
		results = Result.query.order_by(desc(Result.date)).limit(10).all()
		return render_template('index.html', results=results)


@main.route("/about")
def about():
		return render_template('about.html', title='About')

cat/trivia/routes.py
from flask import render_template, request, Blueprint
from flask_login import current_user, login_required
from cat import db
from cat.models import Trivia, Result
from cat.trivia.utils import shuffle, to_dict, get_correct_answers
from sqlalchemy import func
import copy, random

triviaa = Blueprint('triviaa', __name__)


@triviaa.route("/take_trivia")
@login_required
def take_trivia():
	trivia_questions = Trivia.query.order_by(func.random()).all() # randomly retrieve trivia questions from db
	# copy_questions = copy.deepcopy(trivia_questions) # make a copy of original data
	
	global original_questions, copy_questions
	
	original_questions = to_dict(trivia_questions) # convert the data to dict
	copy_questions = copy.deepcopy(original_questions)
	for i in copy_questions.keys():
		random.shuffle(copy_questions[i]) # shuffle the choices
	return render_template('take_trivia.html', title='Play', trivia_questions=copy_questions)

@triviaa.route("/trivia_answers", methods=['POST'])
def trivia_answers():
	accuracy = 0
	answered_answers = {}
	correct_answers = get_correct_answers(original_questions) #collect correct answers
	for q in original_questions.keys():
		answered = request.form[q]
		answered_answers[q] = answered
		if original_questions[q][0] == answered:
			accuracy = accuracy+1

	percent = accuracy/10 # calc accuracy rate and insert into db
	result = Result(percentage=percent, examinee=current_user)
	db.session.add(result)
	db.session.commit()

	print(correct_answers, '\n')
	return render_template('trivia_answers.html', accuracy=accuracy, original=copy_questions, correct=correct_answers, answered=answered_answers)

cat/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from cat import db, bcrypt
from cat.models import User
from cat.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm
from cat.users.utils import send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations! Your account has been created', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.about'))

@users.route("/reset_pass", methods=['GET', 'POST'])
def reset_pass():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email to reset your password will be sent to you. Please check your inbox.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_pass.html', title = 'Reset Password', form = form)

@users.route("/reset/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid token', 'warning')
        return redirect(url_for('users.reset_pass'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form)

cat/templates/about.html
{% extends "layout.html" %}
{% block content %}
<html>

    <body style= "font-family: 'Raleway', serif;">
    	<div style= "background-color: #D68717; background-size: contain; color: white; opacity: 0.9;" class="jumbotron">
	        <p>Cyber Awareness Trivia (CAT) is a web application designed for users to explore the realm of cybersecurity. It serves as an educational platform for anyone who is interested regardless of expertise (or knowledge). The mission is to bring awareness about internet safety and to provide an opportunity for users to challenge their skills with various trivia questions.</p>
    </div><br>   
    <h4>You clicked on a bad link and now you're a target. How do you protect yourself? <a href= "{{ url_for('users.register') }}">Are you up for the challenge?</a> </h4>
    <hr>
    <h3> Check out a sample of the trivia challenges:</h3></div>
    <div>
        <h4>Q: How often should you change you password?</h4>
        <!-- Modal -->
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
          3 months
        </button>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter2">
          1 year
        </button>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter2">
          Never
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Good Job!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                You are right! But why not join today to learn more.
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onClick="location.href='{{ url_for('users.register')}}'">Join Today!</button>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade" id="exampleModalCenter2" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Opps!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Opps! It seems you need to learn some cyber knowledge.
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onClick="location.href='{{ url_for('users.register')}}'">Join Today!</button>
              </div>
            </div>
          </div>
        </div>
    </div>

</html>
{% endblock content %}

cat/templates/index.html
{% extends "layout.html" %}
{% block content %}
<table class="table table-striped table-hover">
          <tr>
            <th>User ID</th>
            <th>Score</th>
            <th>Date</th>
          </tr>
          {% for result in results %}
            <tr>
              <td>{{ result.user_id }}</td>
              <td>{{ "{:.2%}".format(result.percentage) }}</td>
              <td>{{ result.date.strftime('%Y/%m/%d, %H:%M:%S') }}</td>
            </tr>
          {% endfor %}
</table>

<html>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js'></script>
{% block body %}
<body>
  <canvas id = "scoreboard" width = "1000" height = "500"></canvas>
  <script>
    var scoreData = 
    {
      labels : 
      [
        {% for result in results %}
          "{{result.date.strftime('%Y/%m/%d, %H:%M:%S')}}",
        {% endfor %}
      ],
    
      datasets : [
        {
          fillColor: "lightblue",
          pointColor: "orange",
          data : 
          [
            {% for result in results %}
              "{{result.percentage}}",
            {% endfor %}
          ]
        }
      ]
    }
        Chart.defaults.global.animationSteps = 50;
        Chart.defaults.global.tooltipYPadding = 16;
        Chart.defaults.global.tooltipCornerRadius = 0;
        Chart.defaults.global.tooltipTitleFontStyle = "normal";
        Chart.defaults.global.tooltipFillColor = "rgba(0,0,0,0.7)";
        Chart.defaults.global.animationEasing = "easeOutBounce";
        Chart.defaults.global.responsive = true;
        Chart.defaults.global.scaleLineColor = "black";
        Chart.defaults.global.scaleFontSize = 16;
    var mychart = document.getElementById("scoreboard").getContext("2d")
    var CAT_scoreboard = new Chart(mychart).Line(scoreData,
    {
              scaleOverride: false,
              scaleSteps: 10,
              scaleStepWidth: 10,
              scaleStartValue: 0,
              scaleShowVerticalLines: true,
              scaleShowGridLines : true,
              barShowStroke : true,
              scaleShowLabels: true,
              bezierCurve: false,

              options:{
                scales:{
                  yAxes:[{
                    ticks: {
                      max:1
                    }
                  }]
                }
              }

    });

    CAT_scoreboard.options.scales = {
    xAxes: [],
    yAxes: [
      {
        ticks: {
          min: 0,
          max: 1,
          beginAtZero: true,
          stepSize: .25
        }
      }
    ]
  };
  myChart.update();
  </script>
</body>
{% endblock body%}
</html>      
{% endblock content %}

cat/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <link rel="icon" href="{{ url_for('static', filename='icon.ico') }}">


    {% if title %}
        <title>Cyber Awareness Trivia - {{ title }}</title>
    {% else %}
        <title>Cyber Awareness Trivia</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="about">Cyber Awareness Trivia</a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav">
              <li><a href="{{ url_for('main.about') }}">About</a></li>
              <li><a href="{{ url_for('triviaa.take_trivia') }}">Trivia</a></li>
              <li><a href="{{ url_for('main.index') }}">Scoreboard</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
              {% else %}
              <li><a href="{{ url_for('users.login') }}">Login</a></li>
              <li><a href="{{ url_for('users.register') }}">Register</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main role="main" class="container">
      <div class="row">
        <div class="col-md">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>
</body>
</html>

cat/templates/login.html
<!DOCTYPE html>
{% extends "layout.html" %}
{% block content %}
<html>
<head>
    <link rel="stylesheet" href="{{url_for('static', filename = 'materialize.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename = 'style.css')}}">  
</head>

<body>
	<ul class="tabs orange darken-2">
		<li class="tab col s3"><a class="white-text active" href="{{ url_for('users.login') }}">login</a></li>
		<li class="tab col s3"><a class="white-text" href="{{ url_for('users.register') }}">register</a></li>
	</ul>
	<div id="login" class="col s12">
		<form method ="POST" action="" class="col s12">
            {{ form.hidden_tag() }}
			<div class="form-container">
				<h3 class="orange-text">Login</h3>
				<div class="row">
					<div class="input-field col s12">
                            {{ form.email.label(class_="validate" + form.email.name) }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class_="validate") }}
                            {% endif %}
					</div>
				</div>
				<div class="row">
					<div class="input-field col s12">
                            {{ form.password.label(class_="validate" + form.password.name) }}
                            {% if form.password.errors %}
                                {{ form.password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class_="validate") }}
                            {% endif %}
					</div>
				</div><br>
				<div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
				</div>
				<br>
				<center>
					{{ form.submit(class_="btn orange darken-2") }}
					<br>
					<br>
					<a href="{{ url_for('users.reset_pass') }}">Forgot your password?</a>
				</center>
			</div>
		</form>
    </div>

</body>
</html>
{% endblock %}

cat/templates/register.html
<!DOCTYPE html>
{% extends "layout.html" %}
{% block content %}
<html>
<head>
	<link rel="stylesheet" href="{{url_for('static', filename = 'materialize.min.css')}}">
	<link rel="stylesheet" href="{{url_for('static', filename = 'style.css')}}">  
</head>

<body>
	<ul class="tabs orange darken-2">
		<li class="tab col s3"><a class="white-text active" href="{{ url_for('users.login') }}">login</a></li>
		<li class="tab col s3"><a class="white-text" href="{{ url_for('users.register') }}">register</a></li>
	</ul>
	<div id="register" class="col s12">
		<form method ="POST" action="" class="col s12">
			{{ form.hidden_tag() }}
			<div class="form-container">
				<h3 class="orange-text">Join Now</h3>
				<div class="row">
					<div class="input-field col s12">
						{{ form.username.label(class_="validate" + form.username.name) }}
						{% if form.username.errors %}
                    		{{ form.username(class="form-control form-control-lg is-invalid") }}
                        	<div class="invalid-feedback">
                            	{% for error in form.username.errors %}
                             	   <span>{{ error }}</span>
                            	{% endfor %}
                        	</div>
                    	{% else %}
							{{ form.username(class_="validate") }}
                    	{% endif %}
					</div>
				</div>
				<div class="row">
					<div class="input-field col s12">
						{{ form.email.label(class_="validate" + form.email.name) }}
						{% if form.email.errors %}
							{{ form.email(class="form-control form-control-lg is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.email.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.email(class_="validate") }}
						{% endif %}
					</div>
				</div>
				<div class="row">
					<div class="input-field col s12">
                    	{{ form.password.label(class_="validate" + form.password.name) }}
                 		{% if form.password.errors %}
                        	{{ form.password(class="form-control form-control-lg is-invalid") }}
                        	<div class="invalid-feedback">
                            	{% for error in form.password.errors %}
                            	    <span>{{ error }}</span>
                            	{% endfor %}
                        	</div>
                    	{% else %}
                        	{{ form.password(class_="validate") }}
                    	{% endif %}
					</div>
				</div>
				<div class="row">
					<div class="input-field col s12">
                    	{{ form.confirm_password.label(class_="validate" + form.confirm_password.name) }}
                    	{% if form.confirm_password.errors %}
                        	{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        	<div class="invalid-feedback">
                            	{% for error in form.confirm_password.errors %}
                            	    <span>{{ error }}</span>
                            	{% endfor %}
                        	</div>
                    	{% else %}
                     	   {{ form.confirm_password(class_="validate") }}
                    	{% endif %}
					</div>
				</div>
				<center>
					<button class="btn orange darken-2" type="submit" name="action">Register</button>
				</center>
			</div>
		</form>
	</div> 
	
</body>
</html>
{% endblock %}

cat/templates/reset_pass.html
{% extends "layout.html" %}
{% block content %}
<html>
<head>
	<link rel="stylesheet" href="{{url_for('static', filename = 'materialize.min.css')}}">
	<link rel="stylesheet" href="{{url_for('static', filename = 'style.css')}}">  
</head>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class = "form-container">
                <h4 class="orange-text">Reset Password</h4>
                <div class="row">
                        <div class="input-field col s12">
                                {{ form.email.label(class_="validate" + form.email.name) }}
                                {% if form.email.errors %}
                                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.email.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.email(class_="validate") }}
                                {% endif %}
                        </div>
                    </div>
                </div>
            <center>
                    {{ form.submit(class_="btn orange darken-2") }}
            </center>
        </form>

{% endblock content %}

cat/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

cat/templates/take_trivia.html
{% extends "layout.html" %}
{% block content %}
<legend>Good Luck Have Fun</legend>
<form action="{{ url_for('triviaa.trivia_answers') }}" method='POST'>
  <ol>
    {% for trivia in trivia_questions %}
      <h3><li> {{ trivia }} </li></h3>
      {% for answers in trivia_questions[trivia] %}
        {% if answers == None %}
          <!-- continue -->
        {% else %}
          <div>
            <input type='radio' value='{{answers}}' name='{{trivia}}'/>
            <label> {{answers}} </label>
          </div>
        {% endif %}
      {% endfor %}
    {% endfor %}
  </ol><br>
  <input type="submit" class="btn btn-primary btn-block" style="width: 150px;" value="Submit" />
</form>
{% endblock content %}

cat/templates/trivia_answers.html
{% extends "layout.html" %}
{% block content %}
<h1>Correct Answers: <u>{{accuracy}}</u></h1>
<form>
  <ol>
  {% for trivia in original %}
    <h3><li> {{ trivia }} </li></h3>
    {% for answers in original[trivia] %}
      {% if answers == None %}
        <!-- continue -->
      {% else %}
        {% if answers == answered[trivia] == correct[trivia] %}
          <input type='radio' value='{{answers}}' name='{{trivia}}' checked/><label style="color:green">{{answers}}</label><br>
        {% elif answers == correct[trivia] %}
          <input type='radio' value='{{answers}}' name='{{trivia}}'disabled/><label style="color:green">{{answers}}</label><br>
        {% elif answers == answered[trivia] != correct[trivia]%}
          <input type='radio' value='{{answers}}' name='{{trivia}}' checked/><label style="color:red">{{answers}}</label><br>
        {% else %}
          <input type='radio' value='{{answers}}' name='{{trivia}}' disabled/>{{answers}}<br>
        {% endif %}
      {% endif %}
    {% endfor %}
  {% endfor %}
  </ol><br>
</form>
<form action="{{ url_for('triviaa.take_trivia') }}">
    <center><input type='submit' class="btn btn-primary btn-block" style = "width: 150px;"value='Another Trivia' /></center>
</form>
{% endblock content %}